device: cuda

networks: 
  actor:
    hidden_layers: [1024, 512]
    activation: relu
    ortho_init: true
    noise_std_type: fixed
    init_noise_std: 0.3

  critic:
    hidden_layers: [1024, 512]
    activation: relu

  discriminator:
    hidden_layers: [1024, 512]
    activation: relu

algorithm:
  name: amp 
  # ppo
  num_transitions_per_env: 2048
  num_mini_batches: 1
  num_learning_epochs: 4
  clip_param: 0.2
  discount: 0.97
  td_lambda: 0.95
  lr: 3e-4
  max_grad_norm: 1.0
  use_clipped_value_loss: true
  desired_kl: 0.01
  normalize_advantage_per_mini_batch: false

  value_loss_coef: 1.0
  entropy_coef: 0.2

  # amp
  discriminator_buffer_capacity: 100000
  disc_lr: 1e-4
  discriminator_update_interval: 4
  disc_update_epochs: 1
  disc_mini_batches: 4
  disc_grad_penalty_coef: 5.0

  style_reward_lambda: 0.5 
  goal_reward_lambda: 0.5

environment:
  id: "AMPEnv"
  type: "gym:debug"
  num_envs: 1
  seed: 0

  kwargs:
    model_path: "humanoid.xml"
    motion_clips: ["not_exist.pkl"] 
    params:
      max_episode_time: 2.0 
      sim_freq: 120.0
      control_freq: 30.0

runner:
  total_timesteps: 500000
  num_envs: 3
  log_interval: 10
  checkpoint_interval: 50
  checkpoint_ir: 5