device: cuda

networks: 
  actor:
    hidden_layers: [1024, 512]
    activation: relu
    ortho_init: true

  critic:
    hidden_layers: [1024, 512]
    activation: relu
    # ortho_init: true

algorithm:
  name: ppo
  num_transitions_per_env: 2048
  num_mini_batches: 1
  num_learning_epochs: 4
  clip_param: 0.2
  discount: 0.97
  td_lambda: 0.95
  lr: 3e-4
  max_grad_norm: 1.0
  use_clipped_value_loss: true
  desired_kl: 0.01
  normalize_advantage_per_mini_batch: false

  value_loss_coef: 1.0
  entropy_coef: 0.2

environment:
  id: "MountainCarContinuous-v0"
  type: "gym:cpu"
  num_envs: 1
  seed: 0

  kwargs:
    render_mode: "human"

runner:
  total_timesteps: 500000
  num_envs: 3
  log_interval: 10
  checkpoint_interval: 50
  checkpoint_ir: 5