
defaults:
  - framework: amp
  - _self_

# Runtime settings
device: cuda
verbose: false

resume_from: Null 

seed: 1231313
num_envs: 1000

logger:
  use_wandb: True
  wandb_project: "amp-locomotion"
  wandb_run_name: "exp-1"

# Hydra settings
hydra:
  run:
    dir: outputs/${hydra:runtime.choices.algorithm}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false 