
# Main configuration file for motion retargeting training

defaults:
  - train: default
  - model: default
  - _self_

# Runtime settings
device: cuda
verbose: false
visualize_data_first: false

# TRAINING / RETARGETING
source: character1
target: Karim

resume_from: Null #outputs/character1_to_Karim/2026-01-20/21-16-44/skeletal_gan_epoch4200.pt #outputs/character2_to_rub001/2026-01-20/07-50-33/skeletal_gan_epoch600.pt

seed: 1231313

logger:
  use_wandb: True
  wandb_project: "deep-skeletal-retargetting"
  wandb_run_name: "exp-3"

# Hydra settings
hydra:
  run:
    dir: outputs/${source}_to_${target}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false 