
# Main configuration file for motion retargeting training

defaults:
  - train: default
  - model: default
  - _self_

# Runtime settings
device: cuda
verbose: false
visualize_data_first: true

# TRAINING / RETARGETING
source: character1
target: rub001

resume_from: Null #outputs/character1_to_Karim/22-19-57/skeletal_gan_epoch1000.pt

seed: 2

logger:
  use_wandb: True
  wandb_project: "deep-skeletal-retargetting"
  wandb_run_name: "exp-3"

# Hydra settings
hydra:
  run:
    dir: outputs/${source}_to_${target}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false 