block1:
  conv_params:
    in_channels_per_joint: 3
    out_channels_per_joint: 6
    bias: false
    kernel_size: 15
    stride: 2
    padding: 7 # = (kernel_size - 1) // 2
    padding_mode: reflect
    dilation: 1
    groups: 1
  
  norm: true
  activation: true

block2:
  conv_params:
    in_channels_per_joint: 6
    out_channels_per_joint: 12
    bias: true
    kernel_size: 16
    padding: 0 
    stride: 2
    padding_mode: reflect
    dilation: 1
    groups: 1
  
  norm: false
  activation: false