dynamic_encoder:
- conv_params:
  in_channels_per_joint: 4
  out_channels_per_joint: 8
  offset_in_channels: 3
  bias: true
  kernel_size: 15
  stride: 2
  padding_mode: reflect
  dilation: 1
  groups: 1
  type: dynamic
- conv_params:
  in_channels_per_joint: 4
  out_channels_per_joint: 8
  offset_in_channels_per_joint: 6
  bias: true
  kernel_size: 15
  stride: 2
  padding_mode: reflect
  dilation: 1
  groups: 1
  type: dynamic