block1:
  conv_params:
    in_channels_per_joint: 4
    out_channels_per_joint: 8
    offset_in_channels_per_joint: 3
    bias: true
    kernel_size: 15
    stride: 2
    padding: 7 # = (kernel_size - 1) // 2
    padding_mode: reflect
    dilation: 1
    groups: 1
  pool: True


block2:
  conv_params:
    in_channels_per_joint: 8
    out_channels_per_joint: 16
    offset_in_channels_per_joint: 6
    bias: true
    kernel_size: 15
    padding: 7 # = (kernel_size - 1) // 2
    stride: 2
    padding_mode: reflect
    dilation: 1
    groups: 1
  pool: True
  last_pool: True