block1:
  conv_params:
    in_channels_per_joint: 3
    out_channels_per_joint: 6
    bias: true
    kernel_size: 1
    stride: 1
    padding: 0
    padding_mode: constant
    dilation: 1
    groups: 1

  pool_features: True
  last_pool: False

block2:
  conv_params:
    in_channels_per_joint: 6
    out_channels_per_joint: 12
    bias: true
    kernel_size: 1
    stride: 1
    padding: 0
    padding_mode: constant
    dilation: 1
    groups: 1
    
  pool_features: False 
  last_pool: False