
# Main configuration file for motion retargeting training

defaults:
  - train: default
  - model: default
  - _self_

# Runtime settings
device: cuda
verbose: false
visualize_data_first: false

# TRAINING / RETARGETING
source: character1
target: Karim

resume_from: Null

seed: 0

# Hydra settings
hydra:
  run:
    dir: outputs/${source}_to_${target}/${now:%H-%M-%S}
  job:
    chdir: false 