
# Main configuration file for motion retargeting training

defaults:
  - train: default
  - dataset: default
  - data: default
  - model: default
  - _self_

seed: 69

# Runtime settings
device: cpu
verbose: true
visualize_data_first: false
num_workers: 4

resume_from: Null

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false  # Don't change working directory